version: '3.8'

services:
  db:
    image: postgres:15-alpine 
    container_name: postgres_autogestion
    restart: always 
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: autogestion
    volumes:
      - postgres_data:/var/lib/postgresql/data 

volumes:
  postgres_data: